vpc_cidr_block= "20.0.0.0/16"
subnet_cidr_block = "20.0.10.0/24"
availability_zone = "us-east-2a"
env_prefix= "dev"
my_ip = "xxx.xxx.xxx.xxx/32"
instance_type= "t2.micro"
public_key_location="~/.ssh/id_rsa.pub"
